# DO NOT EDIT THIS FILE!! 
# IF MODIFIED IN ANY WAY, YOU WILL RECEIVE 0 FOR THE GRADE!
import unittest
from Lab5 import hollow_right_leaning_parallelogram, number_pattern, sum_of_natural_numbers, centered_star_pyramid

# Test hollow_square function
def test_hollow_right_leaning_parallelogram():
    assert hollow_right_leaning_parallelogram(5) == "    *****\n   *   *\n  *   *\n *   *\n*****"
    assert hollow_right_leaning_parallelogram(4) == "   ****\n  *  *\n *  *\n****"
    assert hollow_right_leaning_parallelogram(3) == "  ***\n * *\n***"

# Test number_pattern function
def test_number_pattern():
    assert number_pattern(4) == "1\n12\n123\n1234"
    assert number_pattern(3) == "1\n12\n123"
    assert number_pattern(1) == "1"

# Test sum_of_natural_numbers function
def test_sum_of_natural_numbers():
    assert sum_of_natural_numbers(5) == 15  # 1+2+3+4+5 = 15
    assert sum_of_natural_numbers(1) == 1
    assert sum_of_natural_numbers(0) == 0
    assert sum_of_natural_numbers(100) == 5050  # 1+2+3+ ...+98+99+100 =5050 : Gauss Example
    assert sum_of_natural_numbers(3) == 6  # 1+2+3 = 6

# Test centered_star_pyramid function
def test_centered_star_pyramid():
    assert centered_star_pyramid(6) == "     *\n    ***\n   *****\n  *******\n *********\n***********"
    assert centered_star_pyramid(4) == "   *\n  ***\n *****\n*******"
    assert centered_star_pyramid(3) == "  *\n ***\n*****"

# Run tests
if __name__ == '__main__':
    test_hollow_right_leaning_parallelogram()
    test_number_pattern()
    test_sum_of_natural_numbers()
    test_centered_star_pyramid()
    print("All tests passed!")
